### PR TITLE
Classy installable

### PR DESCRIPTION
**Pull request by MaNyh**
We can begin with the merge, if you are up to it. My work here is almost done :D

What this branch is capable of:

- installable version of classy_blocks
- automated and reproducible installation of dependencies
- pytest test module
- continious integration using github action runner on a vanilla ubuntu system

The review should focus on the compatability of classy_examples. How can we make use of the installable version in this repository? I did NOT register the package on pypi, you cant install it with "pip install classy_blocks" (yet). you would need to use pip install git+[https-git-link[ to install the package without cloning the repository and installing from source.

Have a look at the sphynx-documentation probably. We could delete it before the merge. Or you consider using it.

Also focus on the test defined in the pytest-module [here](https://github.com/damogranlabs/classy_blocks/blob/classy_installable/tests/test_classy_blocks.py). there are two automatically generated tests in there that i don't understand. we might delete them. the test i wrote is also not want you want in the long term as no assert is used. I think this might be a story for another issue and we could leave it like that.  You know yourself better what needs to be tested and how.

consider a version tag "0.1.0" when merged.

### CODE REVIEW

**Comment by FranzBangar** [comment]
_I need a little more time, working on this and all the underlying stuff at the moment..._
[Please be patient]

**Comment by schperplata** [comment]
Hey MaNyh, although I am not review assignee for this PR, Franz asked me to step in and... well, do my job :)

Although this PR is one of the first things needed to be done with classy blocks also on our (damogran labs) list,
here are a couple of things would do different compared to your PR:

* I would use only one main package description file, that is *setup.py*. That way pkg info is stored in one (and only) place.  
TODO: Get rid of *setup.cfg*. Data like version can go into the package itself in *\_\_init\_\_.py* or *version.py*, also easily accessible in programmatic way. 
* *setup.py* should list pkg requirements directly, that is: populate `install_requires` field. *requirements.txt* should be used for
development and/or test requirements, which are not needed for package to work. This idea comes from [here](https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/).  
TODO: populate *setup.py*->`install_requires` field with actual classy_blocks requirement, while move test and development dependencies to requirement files.  
Personally, I would also separate development dependencies (example, `black` formatter) from test dependencies (`pytest`) to a separate *requirements_dev.txt* and *requirements_test.txt* files respectively. That is (almost) done anyway :).
* Read procedures (`with open()...` blocks) of README, HISTORY and other files in *setup.py* should be performed in a functions, that return that content. 
That way no code is executed unless `setup()` is actually called and IDE tools are not performing anything on import or actions taken on *setup.py* file, like linting.  
TODO: wrap `with open()...` blocks to a separate functions and execute them once needed, in `setup()`.  
* Personally, I would remove "test instructions" and test dependencies from *setup.py*. Package tests - from my point of view - are used in development stage 
where entire repository checkout is necessary, while they are not needed by the end user. Detailed instructions and how-to procedures are (should be) available in *CONTRIBUTING.rst* anyway.  
TODO: remove test stuff from *setup.py* and instead write down how-to contribute in *CONTRIBUTING.rst*.
* Package layout: I would go with /src layout. It is better designed for further package additions (like, adding another tool is just another dir in /src) and better isolate sources from other stuff - maybe one day, there would be a special dir with C/Rust/whatever language source files.  
TODO: create *src* dir on the root and move *classy_blocks* there. Update setup.py to search packages only in src dir, like [here](https://stackoverflow.com/a/50874613/9200430).
* *MANIFEST.in* include a lot of files, which are not really needed by the package end user and shouldn't be part of final distribution. For example, *Makefile* for documentation generation is not needed by the end user, we have online docs for this purpose.  
TODO: cleanup *MANIFEST.in* document of all dependencies, that are not explicitly required by package itself (that is development, test and other files). 
Maybe we don't need anything shipped with wheel, and we don't need *Manifest.in* at all?!  Is *setup.py*->`zip_safe=` setting needed?
* Abstract vs pinned dependencies: It is a good practice to use pinned dependencies only where absolutely necessary, and even than, specify range, not exact version. This adds more freedom to end-user environment, where class_blocks might not be the only dependency using `jinja2` and one might work on HEAD, instead on `3.1.2`.  
TODO: use latest and the greatest versions if possible - remove pinned dependencies or add lowest allowed version for any dependency in *requirements_\*.txt* files and in *setup.py*->`install_requires`.
* Development/test tools should have its own cfg file if possible, for example *pytest.ini*, *black.toml* and *.pylint*. That way it is really obvious how to configure any IDE and, for example, CI actions.
* What is Makefile on the root? I am not familiar with this, although I can see what it is doing from the code. Is this something that `tox` could do (since you already prepared everything, and we would only have one tool)?  
* It is great you've added GitHub actions to perform per-commit tests. Maybe we should do something similar for classy_examples!  
Anyway, I think we should make sure tests are performed on a clean environment with only package and test dependencies installed, and possibly generate some report files, like pip freeze for the times something goes wrong and user inspection is needed.

Overall, this is a great PR. Stuff described above comes from my experiences with packaging and packaging tools from my day job, which are - of course - subjective and might not be the best, but I know for sure some of the points mentioned above bit us before, so why bother repeating them again. :) Feel free to comment and further discuss the ideas!
  
And of course, thank you for your contribution, it is great!

**Comment by MaNyh** [comment]
hey there. i just found your message and want to let you know, that an answer will take approx. 2 weeks. i am currently really busy.

you have a lot of comments and some are not that easy to answer. but i am looking forward for a discussion on all of your comments.

**Review by FranzBangar — APPROVED** [review]
The commit works, the package installs. There's a problem with static files (templates for OF and VTK files), but will be fixed with the next commit.

The comments on this PR from schperplata will be resolved/implemented later within a new branch.

For next PRs, please make a fork of this repository and then make a PR from your fork.

Thank you for your contribution, we can finally get rid of submodules! :)

**Comment by MaNyh** [comment]
I am happy that you are using my work. But I am not happy with me not resolving the remaining questions.

> For next PRs, please make a fork of this repository and then make a PR from your fork.

Sure. I will do that. But i dont understand why this is advantageous. Can you explain?

**Comment by MaNyh** [comment]
> It is a common workflow - fork, commit, pull request.
I am not sure about the fork. I am mostly working on gitlab, also in a professional context. We don't fork for a PR. Is there any obvious advantage?

> What other questions remain? 
@schperplata has listed issues and questions about the PR

**Comment by schperplata** [comment]
> I am not sure about the fork. I am mostly working on gitlab, also in a professional context. We don't fork for a PR. Is there any obvious advantage?

@MaNyh The reason for that might be that in a professional context you are describing, you might be a part of the repository owners or participant, which is a common practice for internal repositories. However, with a public repositories, PR are done almost exclusively over fork - being part of repository owner/moderator/maintainer also grants you some permissions that can have unwanted side effect on a repository that owner itself should know about it and/or have control over it. That being said, don't feel that it is _you_ only, that this concept apply to - anybody outside of repository/organizator owner should do it that way.  
  
About other points of my review: feel free to open a discussion (here) about anything you feel needs to be discused. In any case, certain points will for sure be done as proposed as I happen to have some (bad and good) experiences with current implementation and these things are best solved as fast as possible. One such example is package layout and where and how dependencies are written.

Thank you again, I think we will create a great package, or at least, perform our packaging kung-fu :)

**Comment by MaNyh** [comment]
Thanks to you both for your explanations! It's a good idea to avoid granting write permissions and now the process makes sense to me.

**Pull request merged**
